sudo: required
services:
  - docker

before_install:
  - docker build -t gmarcus/react_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gmarcus/react_test npm test

after_success:
  - docker build -t gmarcus/multi-client ./client
  - docker build -t gmarcus/multi-nginx ./nginx
  - docker build -t gmarcus/multi-server ./server
  - docker build -t gmarcus/multi-worker ./worker
  # Log in to the docker CLI without prompting
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push -t gmarcus/multi-client
  - docker push -t gmarcus/multi-nginx
  - docker push -t gmarcus/multi-server
  - docker push -t gmarcus/multi-worker