language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gmarcus/react_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gmarcus/react_test npm test

after_success:
  - docker build -t gmarcus/multi-client ./client
  - docker build -t gmarcus/multi-nginx ./nginx
  - docker build -t gmarcus/multi-server ./server
  - docker build -t gmarcus/multi-worker ./worker
  # Log in to the docker CLI without prompting
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gmarcus/multi-client
  - docker push gmarcus/multi-nginx
  - docker push gmarcus/multi-server
  - docker push gmarcus/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-442055873559"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY